## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'signal_recovery'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_template become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_signal_recovery' #to modify
description = 'Hardware plugin for instruments from Signal Recovery'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymeasure']
